In [1]:
import pandas as pd

In [2]:
truth_cosmo = pd.read_csv('../data/reto/raw/cosmo.csv')
truth_cosmo

                                                  reto
0       Enseñar la foto más embarazosa de tu teléfono.
1    Cambiar tu foto de WhatsApp y poner una que sa...
2    Enseñar las últimas cinco personas a las que e...
3                              Declararte a tu vecino.
4    Hacerte una foto en una pose ridícula y public...
..                                                 ...
352                    Hacerte el sordo un día entero.
353                    Hacerte el ciego un día entero.
354                 Enviar sólo emojis durante un día.
355  Llamar a uno de tus padres para cantarle una c...
356    Hacerte mal el eyeliner y salir así a la calle.

[357 rows x 1 columns]

In [3]:
truth_uncomo = pd.read_csv('../data/reto/raw/uncomo.csv')
truth_uncomo

                                                 reto
0        Da una vuelta en ropa interior por la calle.
1                       Tírate a la piscina con ropa.
2   Sirve las copas de todo el mundo durante toda ...
3      Haz tantas flexiones como puedas en un minuto.
4                No mires el móvil durante dos horas.
..                                                ...
84  Envía un mensaje sucio a la persona del grupo ...
85  Besa a alguien del grupo durante un mínimo de ...
86              Muestra cuál es tu juguete preferido.
87  Busca por Internet alguna postura extraña que ...
88  Susurra algo atrevido y sugerente al oído de o...

[89 rows x 1 columns]

In [4]:
full_reto = pd.concat([truth_cosmo, truth_uncomo])
full_reto

                                                 reto
0      Enseñar la foto más embarazosa de tu teléfono.
1   Cambiar tu foto de WhatsApp y poner una que sa...
2   Enseñar las últimas cinco personas a las que e...
3                             Declararte a tu vecino.
4   Hacerte una foto en una pose ridícula y public...
..                                                ...
84  Envía un mensaje sucio a la persona del grupo ...
85  Besa a alguien del grupo durante un mínimo de ...
86              Muestra cuál es tu juguete preferido.
87  Busca por Internet alguna postura extraña que ...
88  Susurra algo atrevido y sugerente al oído de o...

[446 rows x 1 columns]

In [6]:
full_reto.to_csv('../data/reto/full_reto.csv', index=False)